

// TOOL:     vlog2tf
// DATE:     Sun Sep 08 23:21:12 2019
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   ps2Top_MSX_XO2
// DESIGN:   ps2Top_MSX_XO2
// FILENAME: ps2Top_MSX_XO2_tf.v
// PROJECT:  ps2msx
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module ps2Top_MSX_XO2_tf();

// Inputs
    reg RSTb;
    reg pclk;
    reg data;
    reg [3:0] Y;


// Outputs
    wire bitA;
    wire [7:0] X;
    wire dataout;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    ps2Top_MSX_XO2 UUT (
        .RSTb(RSTb), 
        .pclk(pclk), 
        .data(data), 
        .Y(Y), 
        .bitA(bitA), 
        .X(X), 
        .dataout(dataout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            RSTb = 0;
            pclk = 0;
            data = 0;
            Y = 0;
    end

endmodule // ps2Top_MSX_XO2_tf